server:
  port: 8082
  # Configuración de sesión
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 300

# Configuracion para PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/adopcion
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update

logging:
  level:
    org:
      springframework:
        web: DEBUG




